import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LateralMenu from "@/components/lateral-menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{ display: "flex" }}>
          {/* Menú lateral */}
          <LateralMenu />

          {/* Contenido principal */}
          <div style={{ marginLeft: "30%", width: "70%", padding: "20px", background: "#f0f0f0", color: "black" }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
